# Generated by Django 5.0.3 on 2026-03-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_password_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitals',
            name='fio2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='loc_alert',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
