# Generated by Django 5.0.3 on 2026-03-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_vitals_fio2_vitals_loc_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='current_device',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='current_flow_rate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='therapy_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
