# Generated by Django 5.0.3 on 2026-03-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_emailotp_reassessmentschedule_assigned_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('signup', 'Signup Verification'), ('login', 'Login Verification'), ('forgot_password', 'Forgot Password')], default='signup', max_length=20),
        ),
    ]
