# Generated by Django 5.0.3 on 2026-03-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_emailotp_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abgdata',
            name='fio2',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
