# Generated by Django 6.0.2 on 2026-03-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_staff_id_staff_staff_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reassessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('type', models.CharField(choices=[('SpO2', 'SpO2'), ('ABG', 'ABG')], max_length=10)),
                ('due_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reassessment',
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='shift_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='shift_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
