# Generated by Django 6.0.3 on 2026-03-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_reassessment_staff_shift_end_staff_shift_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
