# Generated by Django 6.0.3 on 2026-03-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staff_is_verified_staff_otp_staff_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
