# Generated by Django 6.0.3 on 2026-03-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_staff_reset_token_staff_token_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reassessment',
            name='heart_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reassessment',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reassessment',
            name='reassessment_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reassessment',
            name='respiratory_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reassessment',
            name='spo2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reassessment',
            name='due_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reassessment',
            name='type',
            field=models.CharField(choices=[('SpO2', 'SpO2'), ('ABG', 'ABG')], default='SpO2', max_length=10),
        ),
    ]
