# Generated by Django 6.0.3 on 2026-03-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_reassessment_heart_rate_reassessment_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('reassessment_id', models.IntegerField(blank=True, null=True)),
                ('spo2', models.FloatField(blank=True, null=True)),
                ('respiratory_rate', models.FloatField(blank=True, null=True)),
                ('heart_rate', models.FloatField(blank=True, null=True)),
                ('abg_values', models.TextField(blank=True, default='')),
                ('remarks', models.TextField(blank=True, default='')),
                ('entered_by', models.CharField(default='staff', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'staff_checklist',
            },
        ),
    ]
