# Generated by Django 6.0.3 on 2026-03-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_staffchecklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffchecklist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='staffchecklist',
            name='reassessment_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
