# Generated by Django 6.0.3 on 2026-03-18 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_add_updated_at_and_unique_reassessment_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staffchecklist',
            table='reassessment_checklist',
        ),
    ]
