# Generated by Django 6.0.2 on 2026-03-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ABGTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('trend_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'abg_trend',
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('risk_score', models.FloatField(help_text='0–100 scale')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('deterioration_probability', models.FloatField(help_text='0.0–1.0')),
                ('key_factors', models.TextField(blank=True, help_text='JSON string of contributing factors', null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_analysis',
            },
        ),
        migrations.CreateModel(
            name='DeviceSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('device', models.CharField(choices=[('venturi', 'Venturi Mask'), ('nasal', 'Nasal Cannula'), ('high_flow', 'High-Flow Nasal Cannula'), ('non_rebreather', 'Non-Rebreather Mask')], max_length=20)),
                ('rationale', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'device_selection',
            },
        ),
        migrations.CreateModel(
            name='EscalationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('criteria_met', models.BooleanField(default=False)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'escalation_criteria',
            },
        ),
        migrations.CreateModel(
            name='HypoxemiaCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('cause', models.CharField(choices=[('vq_mismatch', 'V/Q Mismatch'), ('hypoventilation', 'Hypoventilation'), ('diffusion', 'Diffusion Impairment'), ('shunt', 'Intrapulmonary Shunt'), ('unknown', 'Unknown')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hypoxemia_cause',
            },
        ),
        migrations.CreateModel(
            name='NIVRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('mode', models.CharField(help_text='e.g. BiPAP, CPAP', max_length=50)),
                ('ipap', models.FloatField(help_text='Inspiratory Positive Airway Pressure (cmH2O)')),
                ('epap', models.FloatField(help_text='Expiratory Positive Airway Pressure (cmH2O)')),
                ('indication', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'niv_recommendation',
            },
        ),
        migrations.CreateModel(
            name='OxygenRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('lpm_required', models.FloatField(help_text='Litres per minute')),
                ('target_spo2', models.FloatField(help_text='Target SpO2 (%)')),
                ('rationale', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'oxygen_requirement',
            },
        ),
        migrations.CreateModel(
            name='OxygenStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('current_flow_rate', models.FloatField(help_text='L/min')),
                ('delivery_device', models.CharField(max_length=100)),
                ('target_spo2_min', models.FloatField(default=88.0)),
                ('target_spo2_max', models.FloatField(default=92.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'oxygen_status',
            },
        ),
        migrations.CreateModel(
            name='ReviewRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('decision', models.CharField(choices=[('accept', 'Accept'), ('override', 'Override')], max_length=10)),
                ('override_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'review_recommendation',
            },
        ),
        migrations.CreateModel(
            name='ScheduleReassessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('interval', models.CharField(choices=[('30m', '30 Minutes'), ('1h', '1 Hour'), ('2h', '2 Hours'), ('4h', '4 Hours')], max_length=5)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'schedule_reassessment',
            },
        ),
        migrations.CreateModel(
            name='TherapyRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('therapy_type', models.CharField(max_length=100)),
                ('flow_rate', models.FloatField(help_text='L/min')),
                ('device', models.CharField(max_length=100)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('precautions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'therapy_recommendation',
            },
        ),
        migrations.CreateModel(
            name='TrendAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('parameter', models.CharField(help_text='e.g. pH, PaO2, SpO2', max_length=50)),
                ('values_json', models.TextField(help_text='JSON array of values with timestamps')),
                ('analysis_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'trend_analysis',
            },
        ),
        migrations.CreateModel(
            name='UrgentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('action_type', models.CharField(help_text='e.g. ICU Transfer, Call Doctor', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'urgent_action',
            },
        ),
    ]
