# Generated by Django 6.0.3 on 2026-03-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0002_remove_abgtrend_trend_summary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oxygenrequirement',
            name='lpm_required',
        ),
        migrations.RemoveField(
            model_name='oxygenrequirement',
            name='rationale',
        ),
        migrations.RemoveField(
            model_name='oxygenrequirement',
            name='target_spo2',
        ),
        migrations.AddField(
            model_name='oxygenrequirement',
            name='hypoxemia_level',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='oxygenrequirement',
            name='oxygen_required',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='oxygenrequirement',
            name='spo2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='oxygenrequirement',
            name='symptoms_level',
            field=models.CharField(default='', max_length=50),
        ),
    ]
