# Generated by Django 6.0.3 on 2026-03-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0003_remove_oxygenrequirement_lpm_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceselection',
            name='flow_range',
            field=models.CharField(default='', max_length=50),
        ),
    ]
