# Generated by Django 6.0.3 on 2026-03-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0004_deviceselection_flow_range'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trendanalysis',
            old_name='created_at',
            new_name='recorded_at',
        ),
        migrations.RemoveField(
            model_name='trendanalysis',
            name='spo2_trend',
        ),
        migrations.RemoveField(
            model_name='trendanalysis',
            name='vitals_trend',
        ),
        migrations.AddField(
            model_name='trendanalysis',
            name='overall_status',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='trendanalysis',
            name='paco2_status',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='trendanalysis',
            name='ph_status',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='trendanalysis',
            name='spo2_status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
