# Generated by Django 6.0.3 on 2026-03-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0005_rename_created_at_trendanalysis_recorded_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aianalysis',
            old_name='created_at',
            new_name='recorded_at',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='deterioration_probability',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='key_factors',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='recommendations',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='risk_score',
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='acidosis',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='confidence_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='hypercapnia',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High')], default='LOW', max_length=20),
        ),
    ]
