# Generated by Django 6.0.3 on 2026-03-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0006_rename_created_at_aianalysis_recorded_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReassessmentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('reassessment_time_minutes', models.IntegerField(default=60)),
                ('due_time', models.DateTimeField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reassessment_schedule',
            },
        ),
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('recommended_device', models.CharField(default='', max_length=100)),
                ('fio2', models.CharField(default='', max_length=50)),
                ('flow_rate', models.CharField(default='', max_length=50)),
                ('accepted', models.IntegerField(default=1)),
                ('override_reason', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'recommendation_log',
            },
        ),
        migrations.CreateModel(
            name='TherapyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('device', models.CharField(default='', max_length=100)),
                ('fio2', models.CharField(default='', max_length=50)),
                ('flow_rate', models.CharField(default='', max_length=50)),
                ('target_spo2', models.CharField(default='', max_length=50)),
                ('next_abg_time', models.CharField(default='', max_length=50)),
                ('rationale', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'therapy_plan',
            },
        ),
    ]
