# Generated by Django 6.0.3 on 2026-03-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0007_reassessmentschedule_recommendationlog_therapyplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulereassessment',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='schedulereassessment',
            name='scheduled_at',
        ),
        migrations.RemoveField(
            model_name='therapyrecommendation',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='therapyrecommendation',
            name='precautions',
        ),
        migrations.RemoveField(
            model_name='therapyrecommendation',
            name='therapy_type',
        ),
        migrations.AddField(
            model_name='reviewrecommendation',
            name='device',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='reviewrecommendation',
            name='fio2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='reviewrecommendation',
            name='flow_rate',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='schedulereassessment',
            name='due_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulereassessment',
            name='reassessment_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='schedulereassessment',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='therapyrecommendation',
            name='fio2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='therapyrecommendation',
            name='next_abg',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='therapyrecommendation',
            name='rationale',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='therapyrecommendation',
            name='target_spo2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='reviewrecommendation',
            name='decision',
            field=models.CharField(default='accepted', max_length=20),
        ),
        migrations.AlterField(
            model_name='therapyrecommendation',
            name='device',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='therapyrecommendation',
            name='flow_rate',
            field=models.CharField(default='', max_length=50),
        ),
    ]
