# Generated by Django 6.0.3 on 2026-03-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0008_remove_schedulereassessment_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulereassessment',
            name='bed_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='schedulereassessment',
            name='patient_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='schedulereassessment',
            name='reassessment_type',
            field=models.CharField(default='SpO2', max_length=50),
        ),
    ]
