# Generated by Django 6.0.3 on 2026-03-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0009_schedulereassessment_bed_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulereassessment',
            name='scheduled_by',
            field=models.CharField(default='staff', max_length=20),
        ),
    ]
