# Generated by Django 6.0.3 on 2026-03-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0010_schedulereassessment_scheduled_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulereassessment',
            old_name='bed_number',
            new_name='bed_no',
        ),
        migrations.RenameField(
            model_name='schedulereassessment',
            old_name='due_time',
            new_name='scheduled_time',
        ),
        migrations.AddField(
            model_name='schedulereassessment',
            name='ward_no',
            field=models.CharField(default='', max_length=20),
        ),
    ]
