# Generated by Django 6.0.3 on 2026-03-17 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0011_rename_bed_number_schedulereassessment_bed_no_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='schedulereassessment',
            table='reassessment_shedule',
        ),
    ]
