# Generated by Django 6.0.3 on 2026-03-12 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbgEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('ph', models.FloatField()),
                ('pao2', models.FloatField()),
                ('paco2', models.FloatField()),
                ('hco3', models.FloatField()),
                ('fio2', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'abg_entry',
            },
        ),
        migrations.CreateModel(
            name='BaselineDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('copd_history', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'baseline_details',
            },
        ),
        migrations.CreateModel(
            name='CurrentSymptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('mmrc_score', models.IntegerField()),
                ('increased_cough', models.BooleanField(default=False)),
                ('increased_sputum', models.BooleanField(default=False)),
                ('wheezing', models.BooleanField(default=False)),
                ('fever', models.BooleanField(default=False)),
                ('chest_tightness', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'current_symptoms',
            },
        ),
        migrations.CreateModel(
            name='GasExchangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('chronic_hypoxemia', models.CharField(max_length=20)),
                ('home_oxygen_use', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gas_exchange_history',
            },
        ),
        migrations.CreateModel(
            name='GoldClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('gold_stage', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gold_classification',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('ward', models.CharField(max_length=100)),
                ('bed_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('stable', 'Stable')], default='stable', max_length=10)),
                ('assigned_doctor_id', models.IntegerField(blank=True, null=True)),
                ('created_by_staff_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'patient',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpirometryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('fev1_percent', models.FloatField()),
                ('fev1_fvc_ratio', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'spirometry_data',
            },
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('spo2', models.IntegerField()),
                ('respiratory_rate', models.IntegerField()),
                ('heart_rate', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('blood_pressure', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vitals',
            },
        ),
        migrations.CreateModel(
            name='ReassessmentChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spo2_checked', models.BooleanField(default=False)),
                ('resp_rate_checked', models.BooleanField(default=False)),
                ('consciousness_checked', models.BooleanField(default=False)),
                ('device_fit_checked', models.BooleanField(default=False)),
                ('abg_checked', models.BooleanField(default=False)),
                ('all_clear', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reassessments', to='patients.patient')),
            ],
            options={
                'db_table': 'reassessment_checklist',
            },
        ),
    ]
