# Generated by Django 6.0.3 on 2026-03-18 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReassessmentChecklist',
        ),
    ]
