# Generated by Django 6.0.3 on 2026-03-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_doctor_is_verified_doctor_otp_doctor_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
