# Generated by Django 6.0.3 on 2026-03-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_doctor_terms_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='reset_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
